apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: fpc-opd-admin
  version: v1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../../base
- harbor.yaml
- service.yaml
- ingress.yaml

transformers:
- cm-suffix-transformer.yaml

configMapGenerator:
- name: update
  behavior: create
  files:
  - update.txt
- name: conf
  behavior: create
  files:
  - vue.conf
  - check.conf
- name: nginx
  behavior: create
  files:
  - nginx.conf
secretGenerator:
- files:
  - filebeat-kafka.yml
  name: filebeat-secret
  type: Opaque